version: '3.9'

services:
  pilgrim:
    image: registry.bhyoo.com/pilgrim:v0.2.5
    networks:
      - traefik-public
      - datadog
    volumes:
      - /mnt/pilgrim:/var/lib/pilgrim
    environment:
      PILGRIM_DB_URL: sqlite:///var/lib/pilgrim/db.sqlite3
      DD_AGENT_HOST: datadog_agent
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.http.routers.pilgrim-insecure.rule=Host(`pilgrim.${DOMAIN?Variable not set}`)
        - traefik.http.routers.pilgrim-insecure.entrypoints=web
        - traefik.http.routers.pilgrim-insecure.middlewares=redirectscheme
        - traefik.http.routers.pilgrim.rule=Host(`pilgrim.${DOMAIN?Variable not set}`)
        - traefik.http.routers.pilgrim.tls=true
        - traefik.http.routers.pilgrim.entrypoints=web-secure
        - traefik.http.services.pilgrim.loadbalancer.server.port=80
        - traefik.http.routers.pilgrim.middlewares=pilgrim-cors
        - traefik.http.middlewares.pilgrim-cors.headers.accesscontrolallowmethods=GET,OPTIONS,POST
        - traefik.http.middlewares.pilgrim-cors.headers.accesscontrolalloworiginlist=https://pilgrim.${DOMAIN?Variable not set}
        - traefik.http.middlewares.pilgrim-cors.headers.accesscontrolmaxage=100
        - traefik.http.middlewares.pilgrim-cors.headers.addvaryheader=false

networks:
  traefik-public:
    external: true
  datadog:
    external: true
