version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/portainer:/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer-insecure.rule=Host(`portainer.${DOMAIN?Variable not set}`)
        - traefik.http.routers.portainer-insecure.entrypoints=web
        - traefik.http.routers.portainer-insecure.middlewares=redirectscheme
        - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN?Variable not set}`)
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.entrypoints=web-secure
        - traefik.http.routers.portainer.service=portainer
        - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  traefik-public:
    external: true
